# Generated by Django 3.2.8 on 2021-10-11 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_relationships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frameworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_relationships.language')),
            ],
        ),
    ]
